// tslint:disable
/**
 * SpecIF Web API
 * Web API for the Specification Integration Facility (SpecIF).
 *
 * OpenAPI spec version: v1.1
 * 
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

export * from "./api";
export * from "./configuration";
